import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
await p.goto("file:///srv/vivat/dev/dist/pages/dealer/news.html");
await p.waitForTimeout(300);
const r = await p.evaluate(() => {
  const el = [...document.querySelectorAll("[data-news-phones] p")][0];
  const rect = el.getBoundingClientRect();
  const s = getComputedStyle(el);
  const span = document.createElement("span");
  span.style.cssText = "position:absolute;visibility:hidden;white-space:nowrap;font:400 16px/22px Onest";
  span.textContent = el.textContent.trim();
  document.body.append(span);
  const w400 = span.getBoundingClientRect().width;
  span.style.font = "500 16px/22px Onest";
  const w500 = span.getBoundingClientRect().width;
  span.remove();
  return { текст: el.textContent.trim(), кегль: s.fontSize, вес: s.fontWeight, ширина_сейчас: Math.round(el.scrollWidth), Regular16: Math.round(w400), Medium16: Math.round(w500) };
});
console.log(r);
await b.close();
